-- Demo data should be added AFTER creating Auth users.
-- For safety, this file creates fictional content only. It does not create passwords.
-- Create these Auth users manually in Supabase Authentication:
-- admin@skhub.test / admin123
-- juan@skhub.test / user123
-- Plus eight youth test accounts if desired.
--
-- After Auth accounts exist, replace the UUID placeholders below with actual IDs
-- from Authentication > Users.

-- Example:
-- insert into profiles(id,full_name,email,role) values
-- ('AUTH-USER-UUID','SK Demo Officer','admin@skhub.test','sk_officer')
-- on conflict(id) do update set role='sk_officer';

-- Fictional content can be inserted using an officer UUID:
-- insert into announcements(title,content,category,created_by,published)
-- values ('Youth Sports Day','Registration is now open for our community sports activity.','Events','OFFICER-UUID',true);

-- The remaining demo records are intentionally templates because Auth user UUIDs
-- are generated by Supabase and cannot safely be guessed.
